#!/bin/sh

if [ ! -f /etc/config/argon ]; then
    touch /etc/config/argon
    uci add argon global
fi

uci set argon.@global[0].primary='#876acc'
uci set argon.@global[0].transparency='0.3'
uci set argon.@global[0].dark_primary='#2f6f27'
# uci set argon.@global[0].progressbar_font='#2e2b60'
# uci set argon.@global[0].online_wallpaper='bing'
uci commit argon
